sudo: true
language: python
python:
  - "3.4"

## http://superuser.com/questions/993718/can-i-install-java-8-on-travis-ci-for-a-python-project
addons:
  apt:
    packages:
      - oracle-java8-installer

# other answer:      
before_install:
  - sudo apt-get update
  - sudo apt-get install oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle   
  
install:
  - "pip install pyyaml"

before_script:
  - mkdir -p bin
  - export PATH=$PATH:$PWD/bin
  - wget --no-check-certificate https://raw.githubusercontent.com/cmungall/biocaddie-gym/master/bin/bc-md-processor.py -O bin/bc-md-processor.py
  - chmod +x bin/*

# command to run tests
script: make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - gh-pages


